---

- name: Restart Apache
  systemd:
          name: httpd
          state: restarted
  when: ansible_os_family == 'RedHat'

- name: Restart Apache
  systemd:
          name: apache2
          state: restarted
  when: ansible_os_family == 'Debian'
